// <auto-generated />
using IntroductionToFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroductionToFramework.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20240418115620_CheckUpdates")]
    partial class CheckUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("IntroductionToFramework.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "w3School",
                            Url = "https://www.w3schools.com/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tech Trends",
                            Url = "https://techtrends.com"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health News",
                            Url = "https://healthnews.com"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Travel Chronicles",
                            Url = "https://travelchronicles.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
